name: poke_app
description: A port of the original pokeapp

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.2+39


environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  flutter_flavorizr: ^2.0.0
  firebase_core: ^2.4.1
  firebase_crashlytics: ^3.0.10
  package_info: ^2.0.2
  logger: ^2.0.2
  get_it: ^7.6.4
  http: ^1.1.0
  flutter_cache_manager: ^3.3.1
  dio: ^5.3.2
  rxdart: ^0.27.7
  url_launcher: ^6.0.3
  shared_preferences: ^2.2.1
  built_value: ^8.4.3
  built_collection: ^5.1.1
  infinite_scroll_pagination: ^4.0.0
  sliver_tools: ^0.2.12
  themed: ^4.0.0
  tuple: ^2.0.2
  circular_reveal_animation: ^2.0.1
  local_hero_with_callback: ^0.0.1
  flutter_animate: ^4.2.0+1
  flutter_animation_progress_bar: ^2.3.1
  rive: ^0.11.17
  expandable: ^5.0.1
  settings_ui: ^2.0.2
  flexible_scrollbar: ^0.1.3
  in_app_review: ^2.0.6
  share_plus: ^7.1.0
  flutter_keyboard_visibility: ^5.4.1
  google_mobile_ads: ^3.0.0
  photo_view: ^0.14.0
  flutter_isolate: ^2.0.4
  in_app_purchase: ^3.1.1
  cached_network_image: ^3.2.3
  soundpool: ^2.4.1
  just_audio: ^0.9.36
  flex_color_scheme: ^7.3.1
  palette_generator: ^0.3.3+3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  graphql_flutter: ^5.1.2

  bordered_text: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
  build_runner: ^2.4.6
  built_value_generator: ^8.6.3
  hive: ^2.2.3
  hive_generator: ^2.0.0
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1
  path_provider: ^2.1.1


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/animations/
    - assets/audio/
  uses-material-design: true

  fonts:
    - family: PokemonSolid
      fonts:
        # Regular
        - asset: assets/fonts/Pokemon-Solid.ttf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For

flutter_native_splash:
  color: "#ff0000"
  image: assets/images/pokeball.png
  android: true
  ios: true

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    dev:
      app:
        name: "PokeApp DEV"

      android:
        applicationId: "com.sealstudios.pokeapp.dev"
        firebase:
          config: "firebase/dev/google-services.json"
      ios:
        bundleId: "com.sealstudios.pokeapp.dev"
        firebase:
          config: "firebase/dev/GoogleService-Info.plist"

    uat:
      app:
        name: "PokeApp UAT"

      android:
        applicationId: "com.sealstudios.pokeapp.uat"
        firebase:
          config: "firebase/uat/google-services.json"
      ios:
        bundleId: "com.sealstudios.pokeapp.uat"
        firebase:
          config: "firebase/uat/GoogleService-Info.plist"

    prod:
      app:
        name: "PokeApp"

      android:
        applicationId: "com.sealstudios.pokeapp.prod"
        firebase:
          config: "firebase/prod/google-services.json"
      ios:
        bundleId: "com.sealstudios.pokeapp.prod"
        firebase:
          config: "firebase/prod/GoogleService-Info.plist"

    paid:
      app:
        name: "PokeApp"

      android:
        applicationId: "com.sealstudios.pokeapp.paid"
        firebase:
          config: "firebase/paid/google-services.json"
      ios:
        bundleId: "com.sealstudios.pokeapp.paid"
        firebase:
          config: "firebase/paid/GoogleService-Info.plist"

