// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOmivGsuy_myEMoEwTld2oHME0EoYXtH0',
    appId: '1:182864126022:web:d61f17c5a7a3bf4b3b6a47',
    messagingSenderId: '182864126022',
    projectId: 'pokeapp-86eec',
    authDomain: 'pokeapp-86eec.firebaseapp.com',
    storageBucket: 'pokeapp-86eec.appspot.com',
    measurementId: 'G-YMNJRZNP8H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCLRDB5rSO5k5zfeFkx2m3eJfayHQ4e-s',
    appId: '1:182864126022:android:425e7bd660e634b93b6a47',
    messagingSenderId: '182864126022',
    projectId: 'pokeapp-86eec',
    storageBucket: 'pokeapp-86eec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZigscMuTyzbPqs0loCNcbEI2KmNaBclY',
    appId: '1:182864126022:ios:1139a530b1e073e33b6a47',
    messagingSenderId: '182864126022',
    projectId: 'pokeapp-86eec',
    storageBucket: 'pokeapp-86eec.appspot.com',
    iosClientId: '182864126022-bb9gl3neq4ddbln8ildsfnbi7g3nn3kj.apps.googleusercontent.com',
    iosBundleId: 'com.sealstudios.pokeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZigscMuTyzbPqs0loCNcbEI2KmNaBclY',
    appId: '1:182864126022:ios:1139a530b1e073e33b6a47',
    messagingSenderId: '182864126022',
    projectId: 'pokeapp-86eec',
    storageBucket: 'pokeapp-86eec.appspot.com',
    iosClientId: '182864126022-bb9gl3neq4ddbln8ildsfnbi7g3nn3kj.apps.googleusercontent.com',
    iosBundleId: 'com.sealstudios.pokeApp',
  );
}
